### ISSUE TITLE
Broken Franka compatibility with polymetis-1064_gbad9b7d5

### ISSUE THREAD

**Issue by wualbert** [facebookresearch/fairo#1202] opened 2022-06-06 07:16 UTC
## Type of Issue

Select the type of issue:
- [X] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
Polymetis no longer works on the Franka robot after updating to version `polymetis-1064_gbad9b7d5`. I reverted to `polymetis-926_g98559149` and it worked again.

## Current Behavior
Polymetis crashes upon running `launch_franka.py robot_client=franka_hardware`. Full error attached below.

## Expected Behavior

The behavior should be the same as the earlier version

## Steps to reproduce

Please add steps to reproduce the bug here along with the stack trace.

## Links to any relevant pastes or documents 

```
[2022-06-05 23:55:24.631] [info] ==== Initializing new RobotClient... ====
[2022-06-05 23:55:24.747] [info] Success.
[2022-06-05 23:55:24.747] [info] Connecting to Franka Emika...
Traceback (most recent call last):
  File "/home/franka/miniconda3/envs/polymetis-2/bin/launch_robot.py", line 94, in <module>
    main()
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/franka/miniconda3/envs/polymetis-2/bin/launch_robot.py", line 90, in main
    client.run()
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/site-packages/polymetis/robot_client/executable_robot_client.py", line 78, in run
    subprocess.run(
  File "/home/franka/miniconda3/envs/polymetis-2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'env', '"PATH=$PATH"', '/home/franka/miniconda3/envs/polymetis-2/bin/franka_panda_client', '/tmp/tmp_tfzidjc']' died with <Signals.SIGABRT: 6>.
[2022-06-05 23:55:24,913][__main__][INFO] - Using sudo to kill subprocess with pid 13002, pgid 13002...
```

**Comment by exhaustin** [comment] 2022-06-06 23:46
Hello @wualbert, can you confirm your Franka FCI version (you should be able to access it via Desk)?

Recently Franka released a new version of libfranka (0.9.0) along with a new version of the FCI (4.2.1), which unfortunately are not backwards compatible. We made changes recently to accommodate users that have upgraded to the newer version, and are working to find a good way to support both version pairs. A fix will be out soon.

**Comment by siddk** [comment] 2022-06-07 06:39
I am also getting this error upon reinstalling Polymetis with both Libfranka 0.9.0 and FCI 4.2.1

**Comment by siddk** [comment] 2022-06-07 06:57
@exhaustin - temporarily, is there a way to install the version of Polymetis say from a week ago? Can we run the `conda install` from a specific commit/are the old conda builds stored somewhere?

**Comment by siddk** [comment] 2022-06-07 17:52
Awesome - was able to build from a prior version; things work as expected!

**Comment by wualbert** [comment] 2022-06-07 23:25
@exhaustin my robot was on libfranka 0.9.0 and FCI 4.2.1
Interestingly, when I built the lastest polymetis from source, the error did not happen.

**Comment by exhaustin** [comment] 2022-06-08 00:40
Indeed I am unable to reproduce the problem on the latest version of Polymetis with FCI 4.2.1
I am also able to build with Polymetis with libfranka on `[f1f46fb](https://github.com/frankaemika/libfranka/tree/f1f46fb008a37eb0d1dba00c971ff7e5a7bfbfd3)` and FCI 4.1.1

@siddk Can you try out one of the above configurations (with the latest Polymetis) and see if you are still getting this issue? If so this issue can be closed.

**Comment by wualbert** [comment] 2022-06-08 01:03
@exhaustin I think the issue is specifically with the binary release. Building from source is fine.

**Comment by exhaustin** [comment] 2022-06-08 03:04
I'm getting the version mismatch issue by using the conda release along with FCI 4.2.1
I will be working to fix that, but I am still unable to reproduce the exact errors you posted above.

**Comment by siddk** [comment] 2022-06-08 14:29
Hey @exhaustin I'm happy to help debug, but with the CoRL deadline around the corner, we've locked all software versions. Happy to take another look late next week?

**Comment by exhaustin** [comment] 2022-06-08 18:01
No hurries at all, good luck with the deadline!

**Comment by exhaustin** [comment] 2022-06-08 19:32
Update on the issue: We realized that another merged PR accidentally reverted the libfranka submodule to an older version. 
After #1211 this issue should be fixed and all Polymetis releases from now on should work out of the box with FCI 4.2.1
Closing the issue, feel free to re-open if I'm wrong and you're still running into the same problem.

**Closed by exhaustin** 2022-06-08 19:32 UTC
